# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/miera_website',
                'doc_host': 'https://Uthallan.github.io',
                'git_url': 'https://github.com/Uthallan/miera_website',
                'lib_path': 'miera_website'},
  'syms': {'miera_website.core': {'miera_website.core.foo': ('core.html#foo', 'miera_website/core.py')}}}
